name: Ruby CI Workflow

on:
  pull_request:
    branches: main

defaults:
  run:
    working-directory: ./api  # 作業ディレクトリを指定

jobs:
    
  ruby-ci:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: todo_test
          MYSQL_USER: todo
          MYSQL_PASSWORD: todo
        ports:
          - 3306:3306
        options: >-
            --health-cmd="mysqladmin ping --silent" 
            --health-interval=10s 
            --health-timeout=5s 
            --health-retries=3

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Rubyのセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Rubyのバージョンを指定
          bundler-cache: true

      # データベースのセットアップ
      - name: Setup database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.github_actions config/database.yml
          bundle exec rails db:prepare

      # RubocopによるLintとFormatチェック
      - name: Run Rubocop for linting and formatting
        run: |
          bundle exec rubocop

      # RSpecのテスト実行
      - name: Run RSpec with coverage
        run: |
          bundle exec rspec